### ISSUE TITLE
Sweetalert

### ISSUE THREAD

**Issue by balarameswar** [Atrox/sweetify-django#14] opened 2020-04-11 07:07 UTC
As per your instruction, I did all the things but in how to download in vs code I am not understood.
 You have to install sweetalert2, the library, itself.
See here: https://sweetalert2.github.io/#download

how to install swwetalert in django . I am using vs code I did pip install --upgrade sweetify.
but how to install the package after this

**Comment by Atrox** [comment] 2020-04-11 09:42
Hey @balarameswar, it is quite unclear what your exact problems are. Do you have issues with setting up sweetify or sweetalert?

Just follow the instructions in the `README` :).

**Comment by balarameswar** [comment] 2020-04-11 11:42
i followed the readme file but I want to know how to import the client side files for sweetaleart?

**Comment by balarameswar** [comment] 2020-04-11 11:45
At first pip install......
then add line on settings.py
then import it on views 
then write sweetify.success
But after doing this I didn't get any sweetify alert.
Plz suggest me what to do next?

**Comment by Atrox** [comment] 2020-04-11 12:56
That means sweetalert itself is missing. Put the following script into your `<head>`:
```html
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>```

**Comment by balarameswar** [comment] 2020-04-11 14:11
i mentioned it but still it is not working.plz help me

**Comment by Atrox** [comment] 2020-04-11 17:12
I'm sorry but "it is not working" is not helping me in helping you... Is there an error in the console?

**Comment by balarameswar** [comment] 2020-04-11 18:16
there is no error in the console.Here I am attaching the screenshot where I write.
![Screenshot (1308)](https://user-images.githubusercontent.com/63491379/79051583-95c17b80-7c4e-11ea-895c-d3085a095c42.png)
![Screenshot (1310)](https://user-images.githubusercontent.com/63491379/79051590-99ed9900-7c4e-11ea-9748-b69ed6b3d7e0.png)
![Screenshot (1311)](https://user-images.githubusercontent.com/63491379/79051592-9c4ff300-7c4e-11ea-9057-61bb7375af72.png)
![Screenshot (1312)](https://user-images.githubusercontent.com/63491379/79051594-9eb24d00-7c4e-11ea-9492-b6900f2c41fa.png)
![Screenshot (1307)](https://user-images.githubusercontent.com/63491379/79051601-a70a8800-7c4e-11ea-8e37-7849762c0231.png)

**Comment by Atrox** [comment] 2020-04-12 08:29
Generally this looks OK and should work. Is there an error in the _browser_ console?

**Comment by balarameswar** [comment] 2020-04-12 13:03
no there is no error in browser console

**Comment by Atrox** [comment] 2020-04-12 16:48
I'm sorry but then I'm not really able to help. I can't magically find out where in your code the problem is :).

I'll close this issue for now. If you find a bug in `sweetify` please open another issue.

**Closed by Atrox** 2020-04-12 16:48 UTC
